import { TO_LIST_OF_SYMBOLS_SYMBOLS } from './TO_LIST_OF_SYMBOLS';
import { V_LIST_OF_SYMBOLS_SYMBOLS } from './V_LIST_OF_SYMBOLS';

export const ALL_SYMBOLS = [
  ...TO_LIST_OF_SYMBOLS_SYMBOLS,
  ...V_LIST_OF_SYMBOLS_SYMBOLS,
];

export { TO_LIST_OF_SYMBOLS_SYMBOLS, V_LIST_OF_SYMBOLS_SYMBOLS };